# Generated by Django 3.2.4 on 2021-07-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210713_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_bt',
            new_name='updated_dt',
        ),
    ]
